name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: America/Los_Angeles
          plugin_lines: yes
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_limit: 20
          plugin_languages_sections: most-used
          plugin_languages_details: bytes-size, percentage
          plugin_languages_ignored: roff, dockerfile, html, css, makefile, qmake, cmake
          plugin_languages_threshold: 0%
          plugin_notable: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_habits_facts: yes
          plugin_achievements: yes
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_achievements_display: compact
